//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach_DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string TacGia { get; set; }
        public Nullable<System.DateTime> NamXB { get; set; }
        public Nullable<int> MaTheLoai { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaBan { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
